"""Add indexes to reviews table

Revision ID: 25a0495d6d03
Revises: 3b59a284d75a
Create Date: 2025-07-31 02:26:55.153280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25a0495d6d03'
down_revision = '3b59a284d75a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index('ix_reviews_area_id', ['area_id'], unique=False)
        batch_op.create_index('ix_reviews_disease_id', ['disease_id'], unique=False)
        batch_op.create_index('ix_reviews_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index('ix_reviews_user_id')
        batch_op.drop_index('ix_reviews_disease_id')
        batch_op.drop_index('ix_reviews_area_id')

    # ### end Alembic commands ###
